"""add department table

Revision ID: b12f060e3b46
Revises: 
Create Date: 2022-11-09 10:35:29.934489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12f060e3b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_department',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('root', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biz_department')
    # ### end Alembic commands ###
